version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: [ "air" ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  # Assuming your Next.js app runs on port 3000
    volumes:
      - ./frontend:/app
    command: ["yarn", "dev"]  # Adjust based on your start command
